#!/bin/sh
ln -sf ./config/configure .
ln -sf ./scripts/new_install.sh ./xvnkb_install
ln -sf ./scripts/new_uninstall.sh ./xvnkb_uninstall
ln -sf ./scripts/xvnkb.lconf.sh ./xvnkb_localeconf
ln -sf ./Makefile.linux ./Makefile.sunos
ln -sf ./Makefile.linux ./tools/Makefile.sunos
ln -sf ../data.c ./tools
ln -sf ../data.h ./tools
ln -sf ../debug.h ./tools
ln -sf ../mode.c ./tools
ln -sf ../mode.h ./tools
ln -sf ../property.c ./tools
ln -sf ../property.h ./tools
ln -sf ../typedefs.h ./tools
ln -sf ../xconfig.c ./tools
ln -sf ../xconfig.h ./tools
ln -sf ../xresource.c ./tools
ln -sf ../xresource.h ./tools
ln -sf ../event.c ./tools
ln -sf ../event.h ./tools
ln -sf ../button.c ./tools
ln -sf ../button.h ./tools
ln -sf ../msgbox.c ./tools
ln -sf ../msgbox.h ./tools
