data.o: data.c data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h
mode.o: mode.c data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h property.h
property.o: property.c /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h debug.h \
  property.h
xconfig.o: xconfig.c xconfig.h data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h property.h
xresource.o: xresource.c data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h
xvnkb_ctrl.o: xvnkb_ctrl.c data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h property.h xconfig.h
xvnkb_setup.o: xvnkb_setup.c data.h /usr/X11R6/include/X11/X.h \
  /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h \
  /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h \
  /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/keysym.h \
  /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/X11/cursorfont.h \
  debug.h typedefs.h mode.h xresource.h
